# Generated by Django 3.1.4 on 2020-12-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pontos_turisticos', '0005_pontoturistico_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao'),
            preserve_default=False,
        ),
    ]
