# Generated by Django 3.1.4 on 2020-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='observacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
